server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/QuainlanCui/springcloud-config.git
#          search-paths:
#            - com.springcloud-config
      label: master
